# Generated by Django 3.2 on 2021-04-14 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nextup_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nextup_api.media')),
                ('runningTime', models.CharField(max_length=30)),
                ('director', models.CharField(max_length=30)),
            ],
            bases=('nextup_api.media',),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('roomId', models.IntegerField(primary_key=True, serialize=False)),
                ('passcode', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='TvShow',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nextup_api.media')),
                ('seasons', models.IntegerField()),
                ('episodeCount', models.IntegerField()),
            ],
            bases=('nextup_api.media',),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('isAdmin', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='media',
            name='id',
        ),
        migrations.AlterField(
            model_name='media',
            name='mediaId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Suggested',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField()),
                ('mediaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nextup_api.media')),
                ('roomId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nextup_api.room')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='hostId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nextup_api.user'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.CharField(max_length=5000)),
                ('mediaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nextup_api.media')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nextup_api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mediaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nextup_api.media')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nextup_api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Last_Showed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField()),
                ('mediaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nextup_api.media')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nextup_api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Dislikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mediaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nextup_api.media')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nextup_api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Delete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField()),
                ('mediaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nextup_api.media')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nextup_api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField()),
                ('mediaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nextup_api.media')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nextup_api.user')),
            ],
        ),
    ]
