# Generated by Django 3.2 on 2021-04-14 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nextup_api', '0002_auto_20210414_0251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delete',
            name='mediaId',
        ),
        migrations.RemoveField(
            model_name='delete',
            name='userId',
        ),
        migrations.AddField(
            model_name='user',
            name='roomId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nextup_api.room'),
        ),
        migrations.DeleteModel(
            name='Add',
        ),
        migrations.DeleteModel(
            name='Delete',
        ),
    ]
