# Generated by Django 3.2 on 2021-04-14 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextup_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='runningTime',
            field=models.IntegerField(blank=True),
        ),
    ]
