# Generated by Django 3.2 on 2021-04-14 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextup_api', '0002_alter_media_runningtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='director',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='episodeCount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='runningTime',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='seasons',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
