# Generated by Django 3.2 on 2021-04-14 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextup_api', '0003_auto_20210414_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='isMovie',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
