# Generated by Django 3.2 on 2021-04-14 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nextup_api', '0004_alter_media_ismovie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isLike', models.BooleanField()),
                ('mediaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nextup_api.media')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nextup_api.user')),
            ],
        ),
        migrations.RemoveField(
            model_name='likes',
            name='mediaId',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='userId',
        ),
        migrations.DeleteModel(
            name='Dislikes',
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
