# Generated by Django 3.2 on 2021-04-15 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nextup_api', '0005_auto_20210414_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='roomId',
        ),
        migrations.CreateModel(
            name='RoomMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nextup_api.room')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nextup_api.user')),
            ],
        ),
    ]
